version: '3'
services:
  nginx:
    container_name: nginx
    build: devops/docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "8085:80"
  php:
    container_name: php
    build: devops/docker/php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    ports:
      - "9000:9000"