version: '3'
services:
  nginx:
    container_name: nginx
    build: devops/docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "8085:80"
  php:
    container_name: php
    build: devops/docker/php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    ports:
      - "9000:9000"
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8081:8080"
    volumes:
      - ./public/swagger.json:/tmp/swagger.json
    environment:
      URL: /tmp/swagger.json
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./public/swagger.json:/swagger.json
    environment:
      SWAGGER_JSON: /swagger.json